name: Deploy to Aruba via FTP

on:
  push:
    branches:
      - main  # Quando fai push su "main", il codice verrà caricato su Aruba

jobs:
  ftp-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Aruba via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./   # Cartella locale con i file (di default la root del repo)
          server-dir: /   # Cartella su Aruba (lascia "/" per la root di public_html)
